name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ws1
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag cr.myelintek.com/myelintek/yolov5:latest
    - name: push to MyelinTek
      run: |
        docker login -u 'robot$github' -p ${{ secrets.CR_TOKEN }} cr.myelintek.com
        docker push cr.myelintek.com/myelintek/yolov5:latest
        docker logout cr.myelintek.com
        docker rmi cr.myelintek.com/myelintek/yolov5:latest