name: BuildTagImage
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ws1
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Print the tag version
        run: echo ${{ steps.get_version.outputs.VERSION }}
      - name: Build the Docker image
        run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag cr.myelintek.com/myelintek/yolov5:${{ steps.get_version.outputs.VERSION }}
      - name: push to MyelinTek
        run: |
          docker login -u 'robot$github' -p ${{ secrets.CR_TOKEN }} cr.myelintek.com
          docker push cr.myelintek.com/myelintek/yolov5:${{ steps.get_version.outputs.VERSION }}
          docker logout cr.myelintek.com